# Generated by Django 4.2.5 on 2023-11-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_likes_follow'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(models.F('user'), models.F('post'), name='LikesComposite'),
        ),
    ]
